name: CI/CD con pruebas de pytest

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      tests_result: ${{ steps.test_outcome.outcome}}
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3
    - name: Configuracion de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    - name: Instalar dependencias
      run: pip install -r requirements.txt
    - name: Ejecución de pruebas
      id: test_outcome
      run: pytest
      continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    if: ${{ always() }}
    steps:
    - name: Crear página según resultado
      run: |
        if [[ "${{ needs.test.outputs.tests_result }}" == "success" ]]; then
            echo "<h1> Despliegue exitoso </h1>" > index.html
            echo "<p> Las pruebas pasaron correctamente. </p>" >> index.html
        else
            echo "<h1 style='color:red;'> Error en CI </h1>" > index.html
            echo "<p> Favor de revisar las pruebas en Github Actions.</p>" >> index.html
        fi
    - name: Subir a Github Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - name: Deploy
      uses: actions/deploy-pages@v4
